[project]
name = "match_my_mentor"
version = "0.1.0"
description = "Add a short description here"
authors = ["PaulKMueller <paulkonstantinmueller@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "flask run"

[dependencies]
flask = ">=3.0.2,<3.1"
